In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import pickle
import pandas as pd
import numpy as np

In [3]:
with open('/content/drive/MyDrive/프로젝트/data/KLyricSentenceDFFinal.p', 'rb') as f:
    df = pickle.load(f)

In [5]:
df_p2 = pd.read_csv('/content/drive/MyDrive/프로젝트/data/poetry.csv')

In [30]:
df_p2

lyric
0                              지금은 남의 땅  빼앗긴 들에도 봄은 오는가
1     나는 온몸에 햇살을 받고 푸른 하늘 푸른 들이 맞붙은 곳으로 가르마 같은 논길을 따...
2     입술을 다문 하늘아 들아 내 맘에는 내 혼자 온 것 같지를 않구나 네가 끌었느냐 누...
3     바람은 내 귀에 속삭이며 한 자욱도 섰지 마라 옷자락을 흔들고 종다리는 울타리 너머...
4     고맙게 잘 자란 보리밭아 간밤 자정이 넘어 내리던 고운 비로 너는 삼단 같은 머리털...
...                                                 ...
9482             다시는 나의 이러한 맘뿐은 때가 되면 그림자 같이 당신한테로 가오리다
9483                                   그립다 말을 할까 하니 그리워
9484                                    그냥 갈까 그래도 다시 한번
9485                  저 산에도 까마귀 들에 까마귀 서산에는 해 진다고 지저귑니다
9486    앞 강물 뒷 강물 흐르는 물은 어서 따라 오라고 따라 가자고 흘러도 연달아 흐릅디다려

[9487 rows x 1 columns]

In [12]:
df_p2['lyric'][1]

'나는 온몸에 햇살을 받고 푸른 하늘 푸른 들이 맞붙은 곳으로 가르마 같은 논길을 따라 꿈 속을 가듯 걸어만 간다'

In [6]:
import re

In [17]:
re.sub(' +', ' ', df_p2['lyric'][0])

'지금은 남의 땅 빼앗긴 들에도 봄은 오는가'

In [7]:
for i in range(len(df_p2)):
    p = re.sub('[^ㄱ-ㅎㅏ-ㅣ가-힣 ]', '', df_p2['lyric'][i])
    p = re.sub(' +', ' ', p).split()
    l = []
    l2 = ''
    for j in range(len(p)):
        if j != 0 and j % 4 == 0:
            l.append(l2)
            l2 = p[j]
        elif j == 0:
            l2 = l2 + p[j]
        else:
            l2 = l2 + ' ' + p[j]
    l.append(l2)
    df_p2.iloc[i,0] = l

In [8]:
df_p2

lyric
0                            [지금은 남의 땅 빼앗긴, 들에도 봄은 오는가]
1     [나는 온몸에 햇살을 받고, 푸른 하늘 푸른 들이, 맞붙은 곳으로 가르마 같은, 논...
2     [입술을 다문 하늘아 들아, 내 맘에는 내 혼자, 온 것 같지를 않구나, 네가 끌었...
3     [바람은 내 귀에 속삭이며, 한 자욱도 섰지 마라, 옷자락을 흔들고 종다리는 울타리...
4     [고맙게 잘 자란 보리밭아, 간밤 자정이 넘어 내리던, 고운 비로 너는 삼단, 같은...
...                                                 ...
9482         [다시는 나의 이러한 맘뿐은, 때가 되면 그림자 같이, 당신한테로 가오리다]
9483                                [그립다 말을 할까 하니, 그리워]
9484                                 [그냥 갈까 그래도 다시, 한번]
9485              [저 산에도 까마귀 들에, 까마귀 서산에는 해 진다고, 지저귑니다]
9486  [앞 강물 뒷 강물, 흐르는 물은 어서 따라, 오라고 따라 가자고 흘러도, 연달아 ...

[9487 rows x 1 columns]

In [39]:
df

title       artist  \
0                 내 손을 잡아          아이유   
1     너의 모든 순간 (Original)          성시경   
2                Timeless       SG 워너비   
3            바람이 불었으면 좋겠어         길구봉구   
4              봄 사랑 벚꽃 말고  HIGH4 (하이포)   
...                   ...          ...   
3391                   소녀           뮤뭉   
3392       꿈처럼 이내 사라져 버리네          박연두   
3393               과일가게총각   나날(NaaNaL)   
3394             Attitude          이보람   
3395                  바다야          홍준영   

                                                  lyric  genre  
0     [느낌이 오잖아, 떨리고 있잖아, 언제까지 눈치만 볼 거니, 네 맘을 말해봐, 딴청...  balad  
1     [이윽고 내가 한눈에, 너를 알아봤을 때, 모든 건 분명 달라지고 있었어, 내 세상...  balad  
2     [어쩜 살아가다 보면, 한 번은 날 찾을지 몰라, 난 그 기대 하나로, 오늘도 힘겹...  balad  
3     [웃는 모습이 너무 아름다운, 그런 너를 기억하면서, 괜찮아 넌 잘할거라 말하던, ...  balad  
4     [길었던 겨우내 줄곧 품이 좀 남는, 밤색 코트, 그 속에 나를 쏙 감추고 걸음을,...  balad  
...                                                 ...    ...  
3391  [손만 닿아도 떨어져버릴 것 같은, 꽃잎 같은 모습을 하고 있는 널 보았어, 아 소...   folk  
3392  [바람은 기억하고 있었고, 바다는 널 품에 안고 있었어, 우리는 늘 그렇듯 살며 잊...   folk  
3393  [우리 동네 과일가게에서, 일하는 총각이 좋아, 갈색머리 우렁찬 목소리에, 나는 빠...   folk  
3394  [빼곡히도 적어 놓았던, 알 수 없던 나의 생각들이, 점점 줄어드는 공간이, 마침표...   folk  
3395  [바다야, 너는 아니, 이곳은 너와 나의 첫 만남이었어, 바다야, 너는 아니, 이곳...   folk  

[5515 rows x 4 columns]

In [9]:
df2 = pd.concat([df,df_p2], axis = 0, ignore_index = True)
df2

title       artist  \
0                  내 손을 잡아          아이유   
1      너의 모든 순간 (Original)          성시경   
2                 Timeless       SG 워너비   
3             바람이 불었으면 좋겠어         길구봉구   
4               봄 사랑 벚꽃 말고  HIGH4 (하이포)   
...                    ...          ...   
14997                  NaN          NaN   
14998                  NaN          NaN   
14999                  NaN          NaN   
15000                  NaN          NaN   
15001                  NaN          NaN   

                                                   lyric  genre  
0      [느낌이 오잖아, 떨리고 있잖아, 언제까지 눈치만 볼 거니, 네 맘을 말해봐, 딴청...  balad  
1      [이윽고 내가 한눈에, 너를 알아봤을 때, 모든 건 분명 달라지고 있었어, 내 세상...  balad  
2      [어쩜 살아가다 보면, 한 번은 날 찾을지 몰라, 난 그 기대 하나로, 오늘도 힘겹...  balad  
3      [웃는 모습이 너무 아름다운, 그런 너를 기억하면서, 괜찮아 넌 잘할거라 말하던, ...  balad  
4      [길었던 겨우내 줄곧 품이 좀 남는, 밤색 코트, 그 속에 나를 쏙 감추고 걸음을,...  balad  
...                                                  ...    ...  
14997         [다시는 나의 이러한 맘뿐은, 때가 되면 그림자 같이, 당신한테로 가오리다]    NaN  
14998                                [그립다 말을 할까 하니, 그리워]    NaN  
14999                                 [그냥 갈까 그래도 다시, 한번]    NaN  
15000              [저 산에도 까마귀 들에, 까마귀 서산에는 해 진다고, 지저귑니다]    NaN  
15001  [앞 강물 뒷 강물, 흐르는 물은 어서 따라, 오라고 따라 가자고 흘러도, 연달아 ...    NaN  

[15002 rows x 4 columns]

In [23]:
with open('PKDFFinal.p', 'wb') as f:
    pickle.dump(df2, f)

In [10]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical

In [11]:
stopwords = ['가', '예', '이', '리가', '하', '오', '지', '도', 
             '마치', '와', '우', '거야', '그', '끼', '번','으로','로'
             '에서', '걸','해','고','얄라리','줘요내']

In [12]:
x_data = []
for i in range(len(df2)):
    x = df2.iloc[i,2]
    
    for line in x:
        xx = []
        for w in line.split():
            if w not in stopwords:
                xx.append(w)
        x_data.append(' '.join(xx))
x_data[0]

'느낌이 오잖아'

In [13]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(x_data)

In [14]:
len(tokenizer.word_index)

122361

In [15]:
vocab_size = len(tokenizer.word_index) + 1 # 0 포함 위해

In [16]:
sequences = []
for line in x_data:
    encoded = tokenizer.texts_to_sequences([line])[0]
    for i in range(2, len(encoded)): # 단어 둘 이하인 문장은 제외(문장을 만들기 어려우므로) 
        sequence = encoded[:i+1]
        sequences.append(sequence)
len(sequences)
# 43만여개의 문장 샘플이 나온다
# ex) 언제까지 눈치만, 언제까지 눈치만 볼, 언제까지 눈치만 볼 거니 ...

439493

In [48]:
tokenizer.word_index['느낌이'], tokenizer.word_index['오잖아']

(1203, 12303)

In [49]:
sequences[0]

[1298, 7234, 139]

In [17]:
np.unique([len(l) for l in sequences], return_counts = True)

(array([  3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,
         16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,
         29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
         42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,
         55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,
         68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,
         81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,
         94,  95,  96,  97,  98,  99, 100, 101, 102]),
 array([220648, 154217,  44457,  15181,   3727,    791,    191,     83,
            36,     17,     11,      4,      3,      3,      3,      2,
             2,      2,      2,      2,      2,      2,      2,      2,
             2,      2,      2,      2,      2,      2,      2,      2,
             2,      2,      2,      2,      2,      2,      2,      2,
             2,      2,      2,      2,      2,      2,      2,      2,
  

In [18]:
sequences = pad_sequences(sequences, maxlen=6, padding='pre')
sequences[0]

array([   0,    0,    0, 1298, 7234,  139], dtype=int32)

In [52]:
print(sequences[20:50])

[[    0     0     0   108  4090  5399]
 [    0     0   108  4090  5399  4205]
 [    0     0     0     1 35828 35829]
 [    0     0     1 35828 35829    61]
 [    0     0     0    63   310   332]
 [    0     0    63   310   332 15560]
 [    0    63   310   332 15560   767]
 [    0     0     0  4091   572    61]
 [    0     0     0   758    51 27133]
 [    0     0   758    51 27133   197]
 [    0     0     0    18   735    66]
 [    0     0    18   735    66   759]
 [    0     0     0  1203 12303 13824]
 [    0     0  1203 12303 13824   357]
 [    0     0     0  1298  7234   139]
 [    0     0  1298  7234   139  1276]
 [    0     0     0    21   107  1435]
 [    0     0     0 21486  9463  7235]
 [    0     0 21486  9463  7235   618]
 [    0     0     0    21   111    85]
 [    0     0    21   111    85   241]
 [    0     0     0    39     1    93]
 [    0     0    39     1    93   604]
 [    0     0     0   740 56109 56110]
 [    0     0   740 56109 56110    61]
 [    0     0     0   332

In [19]:
# 각 샘플 문장의 마지막 단어를 레이블로 분류하기
sequences = np.array(sequences)
X = sequences[:,:-1]
y = sequences[:,-1]

In [25]:
X[0]

array([   0,    0,    0, 1298, 7234], dtype=int32)

In [20]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, LSTM
from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping
from tensorflow.keras.models import load_model

In [ ]:
del m

In [21]:
m = Sequential()
m.add(Embedding(vocab_size, 10))
m.add(LSTM(128, return_sequences=True))
m.add(LSTM(1024))
m.add(Dense(vocab_size, activation = 'softmax'))
m.compile(optimizer = 'adam',loss = 'sparse_categorical_crossentropy', metrics = 'accuracy')

In [22]:
ckp = ModelCheckpoint(filepath = '/content/drive/MyDrive/프로젝트/모델/LSTM8p.h5', monitor = 'loss', save_best_only = True)
m.fit(X,y, epochs = 20, callbacks = [ckp])

Epoch 1/20
13735/13735 [==============================] - 613s 44ms/step - loss: 9.4036 - accuracy: 0.0198
Epoch 2/20
13735/13735 [==============================] - 599s 44ms/step - loss: 8.5886 - accuracy: 0.0400
Epoch 3/20
13735/13735 [==============================] - 595s 43ms/step - loss: 7.8073 - accuracy: 0.0701
Epoch 4/20
13735/13735 [==============================] - 594s 43ms/step - loss: 6.8201 - accuracy: 0.1228
Epoch 5/20
13735/13735 [==============================] - 597s 43ms/step - loss: 5.7761 - accuracy: 0.1881
Epoch 6/20
13735/13735 [==============================] - 599s 44ms/step - loss: 4.8261 - accuracy: 0.2580
Epoch 7/20
13735/13735 [==============================] - 596s 43ms/step - loss: 4.0326 - accuracy: 0.3298
Epoch 8/20
13735/13735 [==============================] - 597s 43ms/step - loss: 3.3736 - accuracy: 0.4019
Epoch 9/20
13735/13735 [==============================] - 595s 43ms/step - loss: 2.8395 - accuracy: 0.4710
Epoch 10/20
13735/13735 [============